### ISSUE TITLE
Box bound support or tricks?

### ISSUE THREAD

**Issue by jlperla** [matthieugomez/LeastSquaresOptim.jl#13] opened 2018-11-30 18:38 UTC
We have a couple of problems where we want to solve nonlinear least squares with constraints (that we do not expect to bind at the solution).  Outside of the constraints the model cannot even be solved (e.g. growth rate less than 0)

With Ceres there are ways to provide box bounds.  Do you have any similar support?  If not, is there a good trick (e.g. penalty functions, etc.) that you have found works well with your setup, keeping in mind that we can't even evaluate our functions outside of the bounds.

**Comment by matthieugomez** [comment] 2018-11-30 20:06
You can add the keyword argument lower and upper. This is very new so I had not added it in the comment. If the x goes outside the box for some iteration, it just takes the closest x still in the box.

https://github.com/matthieugomez/LeastSquaresOptim.jl/blob/master/src/optimizer/dogleg.jl#L146

**Comment by jlperla** [comment] 2018-11-30 20:08
Perfect, thanks!

@chiyahn : give it a shot on our problem, and maybe add in something to the readme if you think it works.

**Comment by chiyahn** [comment] 2018-11-30 23:33
@matthieugomez Thanks for the help. I have tried adding bounds in the toy example from `README.md` file but I am not sure if `lower` is working as expected:
```julia
using LeastSquaresOptim
function rosenbrock(x)
	[1 - x[1], 100 * (x[2]-x[1]^2)]
end
x0 = zeros(2)
optimize(rosenbrock, x0, Dogleg(), lower = fill(0.0, length(x0)))
```
returns the following error:
```
ERROR: TypeError: in #optimize!, in typeassert, expected Array{Array{Float64,1},1}, got Array{Float64,1}
Stacktrace:
 [1] (::getfield(LeastSquaresOptim, Symbol("#kw##optimize!")))(::NamedTuple{(:lower,),Tuple{Array{Float64,1}}}, ::typeof(optimize!), ::LeastSquaresProblemAllocated{Array{Float64,1},Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},Array{Float64,2},getfield(LeastSquaresOptim, Symbol("##3#5")){Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},DiffEqDiffTools.JacobianCache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}}},LeastSquaresOptim.AllocatedDogleg{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}},LeastSquaresOptim.DenseQRAllocatedSolver{Array{Float64,2},Array{Float64,1}}}) at .\none:0
 [2] #optimize!#11(::Base.Iterators.Pairs{Symbol,Array{Float64,1},Tuple{Symbol},NamedTuple{(:lower,),Tuple{Array{Float64,1}}}}, ::Function, ::LeastSquaresProblem{Array{Float64,1},Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},Array{Float64,2},getfield(LeastSquaresOptim, Symbol("##3#5")){Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},DiffEqDiffTools.JacobianCache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}}}}, ::Dogleg{Nothing}) at C:\Users\Chiyoung Ahn\.julia\dev\LeastSquaresOptim\src\types.jl:145
 [3] (::getfield(LeastSquaresOptim, Symbol("#kw##optimize!")))(::NamedTuple{(:lower,),Tuple{Array{Float64,1}}}, ::typeof(optimize!), ::LeastSquaresProblem{Array{Float64,1},Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},Array{Float64,2},getfield(LeastSquaresOptim, Symbol("##3#5")){Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},DiffEqDiffTools.JacobianCache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}}}}, ::Dogleg{Nothing}) at .\none:0
 [4] #optimize#8(::Symbol, ::Base.Iterators.Pairs{Symbol,Array{Float64,1},Tuple{Symbol},NamedTuple{(:lower,),Tuple{Array{Float64,1}}}}, ::Function, ::typeof(rosenbrock), ::Array{Float64,1}, ::Dogleg{Nothing}) at C:\Users\Chiyoung Ahn\.julia\dev\LeastSquaresOptim\src\types.jl:141
 [5] (::getfield(Optim, Symbol("#kw##optimize")))(::NamedTuple{(:lower,),Tuple{Array{Float64,1}}}, ::typeof(optimize), ::Function, ::Array{Float64,1}, ::Dogleg{Nothing}) at .\none:0
 [6] top-level scope at none:0
```
Transforming `lower` argument to `Array{Array{Float64,1},1}` as below
```
using LeastSquaresOptim
function rosenbrock(x)
	[1 - x[1], 100 * (x[2]-x[1]^2)]
end
x0 = zeros(2)
optimize(rosenbrock, x0, Dogleg(), lower = (x -> [x]).(fill(0.0, length(x0))))
```
returns the following error:
```
ERROR: MethodError: no method matching isless(::Array{Float64,1}, ::Float64)
Closest candidates are:
  isless(::Float64, ::Float64) at float.jl:459
  isless(::Missing, ::Any) at missing.jl:66
  isless(::AbstractFloat, ::AbstractFloat) at operators.jl:148
  ...
Stacktrace:
 [1] <(::Array{Float64,1}, ::Float64) at .\operators.jl:260
 [2] <=(::Array{Float64,1}, ::Float64) at .\operators.jl:309
 [3] >=(::Float64, ::Array{Float64,1}) at .\operators.jl:333
 [4] _broadcast_getindex at .\broadcast.jl:574 [inlined]
 [5] getindex at .\broadcast.jl:507 [inlined]
 [6] copy at .\broadcast.jl:758 [inlined]
 [7] materialize at .\broadcast.jl:724 [inlined]
 [8] #optimize!#15(::Float64, ::Float64, ::Float64, ::Int64, ::Float64, ::Bool, ::Bool, ::Int64, ::Array{Array{Float64,1},1}, ::Array{Array{Float64,1},1}, ::typeof(optimize!), ::LeastSquaresProblemAllocated{Array{Float64,1},Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},Array{Float64,2},getfield(LeastSquaresOptim, Symbol("##3#5")){Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},DiffEqDiffTools.JacobianCache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}}},LeastSquaresOptim.AllocatedDogleg{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}},LeastSquaresOptim.DenseQRAllocatedSolver{Array{Float64,2},Array{Float64,1}}}) at C:\Users\Chiyoung Ahn\.julia\dev\LeastSquaresOptim\src\optimizer\dogleg.jl:59
 [9] (::getfield(LeastSquaresOptim, Symbol("#kw##optimize!")))(::NamedTuple{(:lower,),Tuple{Array{Array{Float64,1},1}}}, ::typeof(optimize!), ::LeastSquaresProblem{Array{Float64,1},Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},Array{Float64,2},getfield(LeastSquaresOptim, Symbol("##3#5")){Array{Float64,1},getfield(LeastSquaresOptim, Symbol("##9#10")){typeof(rosenbrock)},DiffEqDiffTools.JacobianCache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}}}}, ::Dogleg{Nothing}) at .\none:0
 [10] #optimize#8(::Symbol, ::Base.Iterators.Pairs{Symbol,Array{Array{Float64,1},1},Tuple{Symbol},NamedTuple{(:lower,),Tuple{Array{Array{Float64,1},1}}}}, ::Function, ::typeof(rosenbrock), ::Array{Float64,1}, ::Dogleg{Nothing}) at C:\Users\Chiyoung Ahn\.julia\dev\LeastSquaresOptim\src\types.jl:141
 [11] (::getfield(Optim, Symbol("#kw##optimize")))(::NamedTuple{(:lower,),Tuple{Array{Array{Float64,1},1}}}, ::typeof(optimize), ::Function, ::Array{Float64,1}, ::Dogleg{Nothing}) at .\none:0
 [12] top-level scope at none:0
```
Seems like there is a problem with indexing, but I am not sure.

**Comment by matthieugomez** [comment] 2018-12-01 01:50
Thanks. Just pushed a fix. Use `checkout` to get the latest version of the package.

**Comment by chiyahn** [comment] 2018-12-01 06:52
I can confirm that the example I posted is now working as intended from c3d1cdce3721d1fd1e78c503cd77702fcc5ddbb5:

```julia
using LeastSquaresOptim
function rosenbrock(x)
	[1 - x[1], 100 * (x[2]-x[1]^2)]
end
x0 = zeros(2)
optimize(rosenbrock, x0, Dogleg(), lower = fill(0.0, length(x0)))
```

Thanks for the update!

**Closed** 2018-12-05 21:56 UTC
